version: '3'

services:
  drupal:
    image: drupal:10.0.4-php8.1-fpm-alpine3.17
    container_name: drupal
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4g3nc14DB
      - POSTGRES_DB=agenciadb
      - DRUPAL_DATABASE_HOST=postgres
      - DRUPAL_DATABASE_PORT=5432
      - DRUPAL_DATABASE_NAME=agenciadb
      - DRUPAL_DATABASE_USER=agencia
      - DRUPAL_DATABASE_PASSWORD=4g3nc14DB
    volumes:
      - ./drupal/modules:/var/www/html/modules
      - ./drupal/themes:/var/www/html/themes
      - ./drupal/profiles:/var/www/html/profiles
      - ./drupal/sites:/var/www/html/sites
    depends_on:
      - postgres
      - redis
    networks:
      - drupal_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=drupal
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      drupal_network:
        ipv4_address: 172.16.238.10

  php:
    image: php:8.1-fpm-alpine
    container_name: php
    restart: always
    volumes:
      - ./drupal:/var/www/html
    networks:
      - drupal_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./drupal:/var/www/html
    depends_on:
      - php
    networks:
      - drupal_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - drupal_network

networks:
  drupal_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24