version: '3'

services:
  drupal:
    image: drupal:10.0.4-php8.1-fpm-alpine3.17
    container_name: drupal
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DRUPAL_DATABASE_HOST=${DRUPAL_DATABASE_HOST}
      - DRUPAL_DATABASE_PORT=${DRUPAL_DATABASE_PORT}
      - DRUPAL_DATABASE_NAME=${DRUPAL_DATABASE_NAME}
      - DRUPAL_DATABASE_USER=${DRUPAL_DATABASE_USER}
      - DRUPAL_DATABASE_PASSWORD=${DRUPAL_DATABASE_PASSWORD}
      - DRUPAL_SITE_NAME=${DRUPAL_SITE_NAME}
      - DRUPAL_SITE_MAIL=${DRUPAL_SITE_MAIL}
      - DRUPAL_ACCOUNT_NAME=${DRUPAL_ACCOUNT_NAME}
      - DRUPAL_ACCOUNT_PASS=${DRUPAL_ACCOUNT_PASS}
      - DRUPAL_ACCOUNT_MAIL=${DRUPAL_ACCOUNT_MAIL}
    volumes:
      - ./drupal/modules:/var/www/html/modules
      - ./drupal/themes:/var/www/html/themes
      - ./drupal/profiles:/var/www/html/profiles
      - ./drupal/sites:/var/www/html/sites
    depends_on:
      - postgres
      - redis
    networks:
      - drupal_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      drupal_network:
        ipv4_address: 172.16.238.10

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./drupal:/var/www/html
    depends_on:
      - drupal
    networks:
      - drupal_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - drupal_network

networks:
  drupal_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
